---
project:
  type: website

website:
  title: "failure_paths"
  navbar:
    left:
      - text: "Python API"
        file: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/kkpdata/faalkansbeheer
        aria-label: GitHub
format:
  html:
    theme: cosmo
    toc: true

quartodoc:
  style: pkgdown
  dir: reference
  title: API Reference
  package: failure_paths
  parser: numpy
  dynamic: True
  rewrite_all_pages: True
  options:
    include_inherited: true
    include_empty: true
    include_attributes: true
    include_classes: true
    include_functions: true
